# Prometheus configuration for Hourglass Performer monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "hourglass_alerts.yml"

scrape_configs:
  # Hourglass Performer metrics
  - job_name: 'hourglass-performer'
    static_configs:
      - targets: ['performer-dev:9090', 'performer-prod:9090']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    
  # Container metrics (if using cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093