server:
  port: 8080
  grpcPort: 9090
  maxConnections: 1000
  readTimeout: 30s
  writeTimeout: 30s
  shutdownTimeout: 30s

orchestrator:
  resources:
    maxCpu: "4"
    maxMemory: "8Gi"
    maxDisk: "50Gi"
    maxContainers: 10
  queue:
    maxQueueSize: 1000
    taskTimeout: 5m
    retryPolicy:
      maxRetries: 3
      backoffMultiplier: 2
  container:
    runtime: "docker"
    network: "bridge"
    pullPolicy: "IfNotPresent"
    env:
      - name: PROXY_URL
        value: "http://localhost:8090"
    labels:
      managed-by: "obsidian"

registry:
  registries:
    - name: "ecr"
      type: "aws-ecr"
      url: ""
      region: "us-east-1"
      credentialSource: "iam-role"
    - name: "ghcr"
      type: "github"
      url: "ghcr.io"
      credentialSource: "secret"
      secretName: "ghcr-token"
    - name: "dockerhub"
      type: "docker-hub"
      url: "docker.io"
      credentialSource: "env"
  cache:
    maxSize: "100Gi"
    ttl: 168h
    cleanupInterval: 1h
  security:
    vulnerabilityScanEnabled: true
    maxCriticalVulnerabilities: 0
    maxHighVulnerabilities: 5
    signatureVerification: false

proxy:
  server:
    port: 8090
    maxConnections: 1000
    readTimeout: 30s
    writeTimeout: 30s
  backends:
    - name: "ethereum"
      url: "https://eth-mainnet.g.alchemy.com/v2/demo"
      rateLimits:
        requestsPerSecond: 10
        burst: 20
      allowedMethods:
        - "eth_call"
        - "eth_getBlockByNumber"
        - "eth_getLogs"
        - "eth_getTransactionReceipt"
      filters:
        - type: "gasLimit"
          parameter: "gas"
          value: "50000000"
    - name: "ipfs"
      url: "https://ipfs.infura.io:5001"
      rateLimits:
        requestsPerSecond: 5
        burst: 10
      allowedMethods:
        - "GET"
        - "POST"
      filters:
        - type: "contentSize"
          value: "10485760"
  logging:
    logRequests: true
    logResponses: false
    samplingRate: 1.0

logging:
  level: "info"
  format: "json"
  outputPath: "stdout"

monitoring:
  metricsEnabled: true
  metricsPort: 9091
  tracingEnabled: false
  tracingEndpoint: ""