apiVersion: v1
kind: Service
metadata:
  name: {{ include "hourglass-operator.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-operator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  - name: health
    port: {{ .Values.service.ports.health }}
    targetPort: health
    protocol: TCP
  {{- if .Values.webhook.enabled }}
  - name: webhook
    port: {{ .Values.service.ports.webhook }}
    targetPort: webhook
    protocol: TCP
  {{- end }}
  selector:
    {{- include "hourglass-operator.selectorLabels" . | nindent 4 }}