apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hourglass-executor.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- include "hourglass-executor.config" . | nindent 4 }}