{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hourglass-executor.executorName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hourglass-executor.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  ingress:
  # Allow from operator namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.operatorNamespace }}
  # Allow from same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  egress:
  # DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  # External API access (HTTPS)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Operator communication
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.operatorNamespace }}
  # Aggregator communication
  - to: []
    ports:
    - protocol: TCP
      port: 9090
  {{- end }}
{{- end }}