{{- if .Values.rbac.create }}
# Role for managing Performers in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "hourglass-executor.executorName" . }}-role
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
rules:
# Performer CRD management
- apiGroups: ["hourglass.eigenlayer.io"]
  resources: ["performers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# Performer status management
- apiGroups: ["hourglass.eigenlayer.io"]
  resources: ["performers/status"]
  verbs: ["get", "patch", "update"]

# Read-only access to Services (for service discovery)
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

# Read-only access to Pods (for monitoring performer status)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Read-only access to Events (for debugging)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]

# ConfigMap access (for configuration updates)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: [{{ include "hourglass-executor.configMapName" . | quote }}]

# Secret access (for operator keys)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: [{{ include "hourglass-executor.secretName" . | quote }}{{- if .Values.secrets.tls.enabled }}, {{ include "hourglass-executor.tlsSecretName" . | quote }}{{- end }}]

{{- with .Values.rbac.additionalRules }}
# Additional rules
{{- toYaml . | nindent 0 }}
{{- end }}

---
# RoleBinding to associate the ServiceAccount with the Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hourglass-executor.executorName" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "hourglass-executor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "hourglass-executor.executorName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}