# Secret for storing operator private keys
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hourglass-executor.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
type: Opaque
data:
  # ECDSA private key (base64 encoded)
  ecdsa-private-key: {{ .Values.secrets.operatorKeys.ecdsaPrivateKey | b64enc | quote }}
  {{- if .Values.secrets.operatorKeys.blsPrivateKey }}
  # BLS private key (base64 encoded)
  bls-private-key: {{ .Values.secrets.operatorKeys.blsPrivateKey | b64enc | quote }}
  {{- end }}

{{- if .Values.secrets.imagePullSecrets.enabled }}
---
# Secret for private container registry access
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hourglass-executor.registrySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  # Docker config JSON (base64 encoded)
  .dockerconfigjson: {{ .Values.secrets.imagePullSecrets.dockerConfigJson | quote }}
{{- end }}

{{- if .Values.secrets.tls.enabled }}
---
# Secret for TLS certificates
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hourglass-executor.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  # TLS certificate (base64 encoded)
  tls.crt: {{ .Values.secrets.tls.cert | quote }}
  # TLS private key (base64 encoded)
  tls.key: {{ .Values.secrets.tls.key | quote }}
  {{- if .Values.secrets.tls.ca }}
  # CA certificate (base64 encoded)
  ca.crt: {{ .Values.secrets.tls.ca | quote }}
  {{- end }}
{{- end }}