{{- include "hourglass-executor.validateValues" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hourglass-executor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hourglass-executor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true