package harness

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Layr-Labs/hourglass-monorepo/hgctl-go/internal/client"
	"github.com/Layr-Labs/hourglass-monorepo/hgctl-go/internal/logger"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/stretchr/testify/require"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest"
	"gopkg.in/yaml.v3"
)

// TestHarness provides a complete testing environment for hgctl integration tests
type TestHarness struct {
	// Chain management
	chainManager *ChainManager
	ChainConfig  *ChainConfig

	// Test environment
	TestDir     string
	ContextName string

	// CLI execution
	cliPath string

	// Clients for verification
	L1Client  *ethclient.Client
	L2Client  *ethclient.Client
	contracts *client.ContractClient

	// Cleanup tracking
	cleanupFns []func()

	// Test logger
	logger *zap.Logger
	t      *testing.T
}

// ChainConfig holds all configuration loaded from chain-config.json
type ChainConfig struct {
	// Contract addresses
	AVSTaskRegistrarAddress  string `json:"avsTaskRegistrarAddress"`
	AVSTaskHookAddressL1     string `json:"avsTaskHookAddressL1"`
	AVSTaskHookAddressL2     string `json:"avsTaskHookAddressL2"`
	KeyRegistrarAddress      string `json:"keyRegistrarAddress"`
	ReleaseManagerAddress    string `json:"releaseManagerAddress"`
	DelegationManagerAddress string `json:"delegationManagerAddress"`
	AllocationManagerAddress string `json:"allocationManagerAddress"`
	StrategyManagerAddress   string `json:"strategyManagerAddress"`

	// Test accounts (generated by our tests)
	OperatorAccountAddress    string `json:"operatorAccountAddress"`
	OperatorAccountPrivateKey string `json:"operatorAccountPk"`
	OperatorKeystorePath      string `json:"operatorKeystorePath"`
	OperatorKeystorePassword  string `json:"operatorKeystorePassword"`
	OperatorAccountPublicKey  string `json:"operatorAccountPublicKey"`

	ExecutorAccountAddress    string `json:"execOperatorAccountAddress"`
	ExecutorAccountPrivateKey string `json:"execOperatorAccountPk"`
	ExecutorKeystorePath      string `json:"execOperatorKeystorePath"`
	ExecutorKeystorePassword  string `json:"execOperatorKeystorePassword"`
	ExecutorAccountPublicKey  string `json:"execOperatorAccountPublicKey"`

	// Existing accounts from chain state
	AVSAccountAddress    string `json:"avsAccountAddress"`
	AVSAccountPrivateKey string `json:"avsAccountPk"`
	AVSAccountPublicKey  string `json:"avsAccountPublicKey"`

	DeployAccountAddress    string `json:"deployAccountAddress"`
	DeployAccountPrivateKey string `json:"deployAccountPk"`
	DeployAccountPublicKey  string `json:"deployAccountPublicKey"`

	AppAccountAddress    string `json:"appAccountAddress"`
	AppAccountPrivateKey string `json:"appAccountPk"`
	AppAccountPublicKey  string `json:"appAccountPublicKey"`

	// Chain details
	L1ChainID int    `json:"-"` // Will be set to 31337
	L2ChainID int    `json:"-"` // Will be set to 31338
	L1RPC     string `json:"-"` // Will be set to http://localhost:8545
	L2RPC     string `json:"-"` // Will be set to http://localhost:9545

	// Fork block numbers
	ForkL1Block int `json:"forkL1Block"`
	ForkL2Block int `json:"forkL2Block"`

	// Environment
	DestinationEnv string `json:"destinationEnv"`
}

// NewTestHarness creates a new test harness instance
func NewTestHarness(t *testing.T) *TestHarness {
	// findProjectRoot returns the directory with go.mod (hgctl-go)
	hgctlRoot := findProjectRoot(t)

	// Create temporary test directory
	testDir, err := os.MkdirTemp("", "hgctl-integration-test-*")
	require.NoError(t, err)

	// Create test logger
	logger := zaptest.NewLogger(t)

	h := &TestHarness{
		TestDir:     testDir,
		ContextName: fmt.Sprintf("test-%d", time.Now().Unix()),
		cliPath:     filepath.Join(hgctlRoot, "bin", "hgctl"),
		logger:      logger,
		t:           t,
		cleanupFns:  []func(){},
	}

	// Add test directory cleanup
	h.cleanupFns = append(h.cleanupFns, func() {
		os.RemoveAll(testDir)
	})

	return h
}

// Setup initializes the test environment
func (h *TestHarness) Setup() error {
	h.logger.Info("Setting up test harness")

	// 1. Initialize chain manager
	h.chainManager = NewChainManager(h.logger)

	// 2. Ensure chains are running
	if err := h.chainManager.EnsureChainsRunning(); err != nil {
		return fmt.Errorf("failed to ensure chains are running: %w", err)
	}

	// Add chain cleanup
	h.cleanupFns = append(h.cleanupFns, func() {
		h.chainManager.Cleanup()
	})

	// 3. Load chain configuration
	config, err := h.chainManager.LoadChainConfig()
	if err != nil {
		return fmt.Errorf("failed to load chain config: %w", err)
	}
	h.ChainConfig = config

	// Set runtime values
	h.ChainConfig.L1ChainID = 31337
	h.ChainConfig.L2ChainID = 31338
	h.ChainConfig.L1RPC = "http://localhost:8545"
	h.ChainConfig.L2RPC = "http://localhost:9545"

	// 3. Wait for chains to be ready
	h.logger.Info("Waiting for chains to be ready")
	l1Client, err := ethclient.Dial(h.ChainConfig.L1RPC)
	if err != nil {
		return fmt.Errorf("failed to connect to L1: %w", err)
	}
	h.L1Client = l1Client

	l2Client, err := ethclient.Dial(h.ChainConfig.L2RPC)
	if err != nil {
		return fmt.Errorf("failed to connect to L2: %w", err)
	}
	h.L2Client = l2Client

	// Wait for both chains
	if err := h.chainManager.WaitForAnvil(l1Client); err != nil {
		return fmt.Errorf("L1 not ready: %w", err)
	}
	if err := h.chainManager.WaitForAnvil(l2Client); err != nil {
		return fmt.Errorf("L2 not ready: %w", err)
	}

	// 4. Initialize contract client
	// Create a proper logger that implements the logger.Logger interface
	testLogger := logger.NewLogger(true) // verbose mode for tests
	contractClient, err := client.NewContractClientWithSigner(
		h.ChainConfig.L1RPC,
		h.ChainConfig.AVSAccountPrivateKey,
		testLogger,
	)
	if err != nil {
		return fmt.Errorf("failed to create contract client: %w", err)
	}
	h.contracts = contractClient

	// 5. Create test context by writing config file
	// Since hgctl doesn't have a 'context create' command, we'll create
	// a minimal config file with our test context
	if err := h.createTestContext(); err != nil {
		return fmt.Errorf("failed to create test context: %w", err)
	}

	h.logger.Info("Test harness setup complete")
	return nil
}

// Teardown cleans up all test resources
func (h *TestHarness) Teardown() {
	h.logger.Info("Tearing down test harness")

	// Execute cleanup functions in reverse order
	for i := len(h.cleanupFns) - 1; i >= 0; i-- {
		h.cleanupFns[i]()
	}

	// Close clients
	if h.L1Client != nil {
		h.L1Client.Close()
	}
	if h.L2Client != nil {
		h.L2Client.Close()
	}
}

// ExecuteCLI runs hgctl with the given arguments
func (h *TestHarness) ExecuteCLI(args ...string) (*CLIResult, error) {
	executor := NewCLIExecutor(h.cliPath, h.TestDir)

	// Set environment variables for the test context
	// Note: The executor already sets HGCTL_CONFIG_DIR to use our test config
	if h.ChainConfig != nil {
		// Add 0x prefix to private key if not present
		privateKey := h.ChainConfig.OperatorAccountPrivateKey
		if !strings.HasPrefix(privateKey, "0x") {
			privateKey = "0x" + privateKey
		}
		executor.Env = append(executor.Env,
			fmt.Sprintf("ETH_RPC_URL=%s", h.ChainConfig.L1RPC),
			fmt.Sprintf("PRIVATE_KEY=%s", privateKey),
		)
	}

	return executor.Execute(args...)
}

// ExecuteCLIWithInput runs hgctl with stdin input
func (h *TestHarness) ExecuteCLIWithInput(input string, args ...string) (*CLIResult, error) {
	executor := NewCLIExecutor(h.cliPath, h.TestDir)

	// Set environment variables for the test context
	// Note: The executor already sets HGCTL_CONFIG_DIR to use our test config
	if h.ChainConfig != nil {
		// Add 0x prefix to private key if not present
		privateKey := h.ChainConfig.OperatorAccountPrivateKey
		if !strings.HasPrefix(privateKey, "0x") {
			privateKey = "0x" + privateKey
		}
		executor.Env = append(executor.Env,
			fmt.Sprintf("ETH_RPC_URL=%s", h.ChainConfig.L1RPC),
			fmt.Sprintf("PRIVATE_KEY=%s", privateKey),
		)
	}

	return executor.ExecuteWithInput(input, args...)
}

// WaitForTransaction waits for a transaction to be mined
func (h *TestHarness) WaitForTransaction(ctx context.Context, txHash string) error {
	// Parse the transaction hash and determine which chain
	// For now, assume L1
	return h.waitForTransactionOnChain(ctx, h.L1Client, txHash)
}

func (h *TestHarness) waitForTransactionOnChain(ctx context.Context, client *ethclient.Client, txHash string) error {
	h.logger.Info("Waiting for transaction", zap.String("hash", txHash))

	ticker := time.NewTicker(500 * time.Millisecond)
	defer ticker.Stop()

	timeout := time.After(30 * time.Second)

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-timeout:
			return fmt.Errorf("timeout waiting for transaction %s", txHash)
		case <-ticker.C:
			receipt, err := client.TransactionReceipt(ctx, common.HexToHash(txHash))
			if err == nil && receipt != nil {
				if receipt.Status == 0 {
					return fmt.Errorf("transaction %s failed", txHash)
				}
				h.logger.Info("Transaction mined", zap.String("hash", txHash), zap.Uint64("block", receipt.BlockNumber.Uint64()))
				return nil
			}
		}
	}
}

// Helper methods for test setup

// CreateTestKeystores creates all necessary keystores for testing
func (h *TestHarness) CreateTestKeystores(t *testing.T) {
	// Create operator ECDSA keystore
	result, err := h.ExecuteCLIWithInput("password\npassword\n",
		"keystore", "create",
		"--context", h.ContextName,
		"--name", "operator-ecdsa",
		"--type", "ecdsa")
	require.NoError(t, err)
	result.AssertSuccess(t)

	// Create operator BN254 keystore
	result, err = h.ExecuteCLIWithInput("bn254-password\nbn254-password\n",
		"keystore", "create",
		"--context", h.ContextName,
		"--name", "operator-bn254",
		"--type", "bn254")
	require.NoError(t, err)
	result.AssertSuccess(t)
}

// RegisterTestOperator completes operator registration flow
func (h *TestHarness) RegisterTestOperator() error {
	result, err := h.ExecuteCLIWithInput("password\n",
		"register",
		"--context", h.ContextName,
		"--keystore", "operator-ecdsa",
		"--allocation-delay", "1")
	if err != nil {
		return err
	}
	if result.ExitCode != 0 {
		return fmt.Errorf("operator registration failed: %s", result.Stderr)
	}
	return nil
}

// RegisterTestOperatorKeys registers all necessary keys
func (h *TestHarness) RegisterTestOperatorKeys() error {
	result, err := h.ExecuteCLIWithInput("bn254-password\n",
		"register-key",
		"--context", h.ContextName,
		"--keystore", "operator-bn254",
		"--operator-address", h.ChainConfig.OperatorAccountAddress,
		"--avs", h.ChainConfig.AVSTaskRegistrarAddress,
		"--operator-set-id", "0")
	if err != nil {
		return err
	}
	if result.ExitCode != 0 {
		return fmt.Errorf("key registration failed: %s", result.Stderr)
	}
	return nil
}

// createTestContext creates a minimal context config file for testing
func (h *TestHarness) createTestContext() error {
	// Create config directory
	configDir := filepath.Join(h.TestDir, ".hgctl")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Create minimal config with test context
	contextConfig := map[string]interface{}{
		"rpcUrl":          h.ChainConfig.L1RPC,
		"networkId":       h.ChainConfig.L1ChainID,
		"executorAddress": "127.0.0.1:9090", // Default executor address
	}

	config := map[string]interface{}{
		"currentContext": h.ContextName,
		"contexts": map[string]interface{}{
			h.ContextName: contextConfig,
		},
	}

	// Write config file
	configFile := filepath.Join(configDir, "config.yaml")
	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	if err := os.WriteFile(configFile, data, 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	h.logger.Info("Created test context config",
		zap.String("context", h.ContextName),
		zap.String("config", configFile))

	// Now set the contract addresses using the context set command
	if err := h.setContractAddresses(); err != nil {
		return fmt.Errorf("failed to set contract addresses: %w", err)
	}

	return nil
}

// setContractAddresses uses the context set command to configure contract addresses
func (h *TestHarness) setContractAddresses() error {
	if h.ChainConfig == nil {
		return nil // No chain config, nothing to set
	}

	// Set delegation manager if available
	if h.ChainConfig.DelegationManagerAddress != "" {
		result, err := h.ExecuteCLI("context", "set", 
			"--delegation-manager", h.ChainConfig.DelegationManagerAddress)
		if err != nil {
			return fmt.Errorf("failed to set delegation manager: %w", err)
		}
		if result.ExitCode != 0 {
			return fmt.Errorf("context set failed: %s", result.Stderr)
		}
		h.logger.Info("Set delegation manager address", 
			zap.String("address", h.ChainConfig.DelegationManagerAddress))
	}

	// Set allocation manager if available
	if h.ChainConfig.AllocationManagerAddress != "" {
		result, err := h.ExecuteCLI("context", "set", 
			"--allocation-manager", h.ChainConfig.AllocationManagerAddress)
		if err != nil {
			return fmt.Errorf("failed to set allocation manager: %w", err)
		}
		if result.ExitCode != 0 {
			return fmt.Errorf("context set failed: %s", result.Stderr)
		}
		h.logger.Info("Set allocation manager address", 
			zap.String("address", h.ChainConfig.AllocationManagerAddress))
	}

	// Set strategy manager if available
	if h.ChainConfig.StrategyManagerAddress != "" {
		result, err := h.ExecuteCLI("context", "set", 
			"--strategy-manager", h.ChainConfig.StrategyManagerAddress)
		if err != nil {
			return fmt.Errorf("failed to set strategy manager: %w", err)
		}
		if result.ExitCode != 0 {
			return fmt.Errorf("context set failed: %s", result.Stderr)
		}
		h.logger.Info("Set strategy manager address", 
			zap.String("address", h.ChainConfig.StrategyManagerAddress))
	}

	// Set release manager if available
	if h.ChainConfig.ReleaseManagerAddress != "" {
		result, err := h.ExecuteCLI("context", "set", 
			"--release-manager", h.ChainConfig.ReleaseManagerAddress)
		if err != nil {
			return fmt.Errorf("failed to set release manager: %w", err)
		}
		if result.ExitCode != 0 {
			return fmt.Errorf("context set failed: %s", result.Stderr)
		}
		h.logger.Info("Set release manager address", 
			zap.String("address", h.ChainConfig.ReleaseManagerAddress))
	}

	return nil
}

// CompleteOperatorSetup performs full operator setup through AVS registration
func (h *TestHarness) CompleteOperatorSetup() error {
	// 1. Create keystores
	h.CreateTestKeystores(h.t)

	// 2. Register as operator
	if err := h.RegisterTestOperator(); err != nil {
		return err
	}

	// 3. Register keys
	if err := h.RegisterTestOperatorKeys(); err != nil {
		return err
	}

	// 4. Register with AVS
	result, err := h.ExecuteCLI("register-avs",
		"--context", h.ContextName,
		"--keystore", "operator-ecdsa",
		"--avs", h.ChainConfig.AVSTaskRegistrarAddress,
		"--operator-set-ids", "0",
		"--socket", "http://operator.example.com:8080")
	if err != nil {
		return err
	}
	if result.ExitCode != 0 {
		return fmt.Errorf("AVS registration failed: %s", result.Stderr)
	}

	return nil
}

// GetBeaconETHStrategy returns the address of the BeaconETH strategy
func (h *TestHarness) GetBeaconETHStrategy() string {
	// This is a well-known address for BeaconETH strategy on testnet
	// You may need to adjust based on your deployment
	return "0xbeaC0eeEeeeeEEeEeEEEEeeEEeEeeeEeeEEBEaC0"
}

// Verification helpers

// VerifyCompleteOperatorSetup verifies all aspects of operator setup
func (h *TestHarness) VerifyCompleteOperatorSetup(t *testing.T) {
	_ = context.Background()

	// Verify operator registration
	h.VerifyOperatorRegistration(t, h.ChainConfig.OperatorAccountAddress)

	// Verify key registration
	h.VerifyKeyRegistration(t, h.ChainConfig.OperatorAccountAddress, h.ChainConfig.AVSTaskRegistrarAddress, 0)

	// Verify AVS registration
	h.VerifyAVSRegistration(t, h.ChainConfig.OperatorAccountAddress, h.ChainConfig.AVSTaskRegistrarAddress, 0)
}

// VerifyOperatorRegistration checks if operator is registered
func (h *TestHarness) VerifyOperatorRegistration(t *testing.T, address string) {
	// Implementation depends on contract client methods
	// This is a placeholder
	h.logger.Info("Verifying operator registration", zap.String("address", address))
}

// VerifyKeyRegistration checks if keys are registered
func (h *TestHarness) VerifyKeyRegistration(t *testing.T, operator, avs string, opSetID uint32) {
	// Implementation depends on contract client methods
	h.logger.Info("Verifying key registration",
		zap.String("operator", operator),
		zap.String("avs", avs),
		zap.Uint32("opSetID", opSetID))
}

// VerifyAVSRegistration checks if operator is registered to AVS
func (h *TestHarness) VerifyAVSRegistration(t *testing.T, operator, avs string, opSetID uint32) {
	// Implementation depends on contract client methods
	h.logger.Info("Verifying AVS registration",
		zap.String("operator", operator),
		zap.String("avs", avs),
		zap.Uint32("opSetID", opSetID))
}

// VerifyAllocation checks if allocation is correct
func (h *TestHarness) VerifyAllocation(t *testing.T, operator, avs, strategy string, opSetID uint32) {
	// Implementation depends on contract client methods
	h.logger.Info("Verifying allocation",
		zap.String("operator", operator),
		zap.String("avs", avs),
		zap.String("strategy", strategy),
		zap.Uint32("opSetID", opSetID))
}

// Helper functions

func findProjectRoot(t *testing.T) string {
	// Start from current directory and walk up to find go.mod
	dir, err := os.Getwd()
	require.NoError(t, err)

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			// Found go.mod, this should be hourglass-monorepo
			return dir
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			// Reached root without finding go.mod
			t.Fatal("Could not find project root")
		}
		dir = parent
	}
}
