version: '3.8'

services:
  executor:
    image: public.ecr.aws/z6g0f8n7/eigenlayer-hourglass:v0.1.0_130a7dc
    # build:
    #   context: ..
    #   dockerfile: ponos/Dockerfile
    networks:
      - hourglass-demo
    ports:
      - "127.0.0.1:9090:9090"
    command:
      - "executor"
      - "run"
      - "--config"
      - "/ponos-config/executor.yaml"
      - "--performer-network-name"
      - "custom-network"
    volumes:
      - .:/ponos-config
      - /var/run/docker.sock:/var/run/docker.sock # required for DinD
  aggregator:
    image: public.ecr.aws/z6g0f8n7/eigenlayer-hourglass:v0.1.0_130a7dc
    networks:
      - hourglass-demo
    ports:
      - "127.0.0.1:9091:9091"
    command:
      - "aggregator"
      - "run"
      - "--config"
      - "/ponos-config/aggregator.yaml"
networks:
  hourglass-demo:
    driver: bridge
