version: '3.8'

services:
  executor:
    # image: public.ecr.aws/z6g0f8n7/eigenlayer-hourglass:v0.1.0_a14a58e
    build:
      context: ..
      dockerfile: ponos/Dockerfile
    networks:
      - hourglass-demo
    ports:
      - "127.0.0.1:9090:9090"
    command:
      - "executor"
      - "run"
      - "--config"
      - "/ponos-config/executor.yaml"
      - "--performer-network-name"
      - "custom-network"
    volumes:
      - .:/ponos-config
      - /var/run/docker.sock:/var/run/docker.sock # required for DinD
  aggregator:
    # image: public.ecr.aws/z6g0f8n7/eigenlayer-hourglass:v0.1.0_a14a58e
    build:
      context: ..
      dockerfile: ponos/Dockerfile
    networks:
      - hourglass-demo
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:8081:8081"
    environment:
      MAILBOX_CONTRACT_ADDRESS_OVERRIDE: "0x7306a649b451ae08781108445425bd4e8acf1e00"
    command:
      - "aggregator"
      - "run"
      - "--config"
      - "/ponos-config/aggregator-chain.yaml"
    volumes:
      - .:/ponos-config
networks:
  hourglass-demo:
    driver: bridge
