version: '3.8'

services:
  aggregator:
    command:
      - "aggregator"
      - "run"
    ports:
      - "8080:8080"
    environment: {}
    restart: unless-stopped
  executor:
    image: public.ecr.aws/z6g0f8n7/eigenlayer-hourglass:latest
    command:
      - "executor"
      - "run"
