{{- if .Values.aggregator.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aggregator.secretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.executor.secret.data }}
{{- range $k, $v := .Values.executor.secret.data }}
  {{ $k }}: '{{ $v | b64enc }}'
{{- end }}
{{- else }}
  {}
{{- end }}
{{- end }}

