// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterType int32

const (
	FilterType_FILTER_TYPE_UNSPECIFIED  FilterType = 0
	FilterType_FILTER_TYPE_GAS_LIMIT    FilterType = 1
	FilterType_FILTER_TYPE_CONTENT_SIZE FilterType = 2
	FilterType_FILTER_TYPE_HEADER       FilterType = 3
	FilterType_FILTER_TYPE_PATH         FilterType = 4
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "FILTER_TYPE_UNSPECIFIED",
		1: "FILTER_TYPE_GAS_LIMIT",
		2: "FILTER_TYPE_CONTENT_SIZE",
		3: "FILTER_TYPE_HEADER",
		4: "FILTER_TYPE_PATH",
	}
	FilterType_value = map[string]int32{
		"FILTER_TYPE_UNSPECIFIED":  0,
		"FILTER_TYPE_GAS_LIMIT":    1,
		"FILTER_TYPE_CONTENT_SIZE": 2,
		"FILTER_TYPE_HEADER":       3,
		"FILTER_TYPE_PATH":         4,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_proxy_proto_enumTypes[0].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_api_proto_proxy_proto_enumTypes[0]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{0}
}

type BackendStatus int32

const (
	BackendStatus_BACKEND_STATUS_UNSPECIFIED  BackendStatus = 0
	BackendStatus_BACKEND_STATUS_HEALTHY      BackendStatus = 1
	BackendStatus_BACKEND_STATUS_UNHEALTHY    BackendStatus = 2
	BackendStatus_BACKEND_STATUS_CIRCUIT_OPEN BackendStatus = 3
)

// Enum value maps for BackendStatus.
var (
	BackendStatus_name = map[int32]string{
		0: "BACKEND_STATUS_UNSPECIFIED",
		1: "BACKEND_STATUS_HEALTHY",
		2: "BACKEND_STATUS_UNHEALTHY",
		3: "BACKEND_STATUS_CIRCUIT_OPEN",
	}
	BackendStatus_value = map[string]int32{
		"BACKEND_STATUS_UNSPECIFIED":  0,
		"BACKEND_STATUS_HEALTHY":      1,
		"BACKEND_STATUS_UNHEALTHY":    2,
		"BACKEND_STATUS_CIRCUIT_OPEN": 3,
	}
)

func (x BackendStatus) Enum() *BackendStatus {
	p := new(BackendStatus)
	*p = x
	return p
}

func (x BackendStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_proxy_proto_enumTypes[1].Descriptor()
}

func (BackendStatus) Type() protoreflect.EnumType {
	return &file_api_proto_proxy_proto_enumTypes[1]
}

func (x BackendStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendStatus.Descriptor instead.
func (BackendStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendName   string                 `protobuf:"bytes,1,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ContainerId   string                 `protobuf:"bytes,6,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_proto_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Latency       *durationpb.Duration   `protobuf:"bytes,4,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_proto_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

type BackendConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	RateLimits     *RateLimits            `protobuf:"bytes,3,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`
	AllowedMethods []string               `protobuf:"bytes,4,rep,name=allowed_methods,json=allowedMethods,proto3" json:"allowed_methods,omitempty"`
	Filters        []*Filter              `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CircuitBreaker *CircuitBreakerConfig  `protobuf:"bytes,7,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_api_proto_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *BackendConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackendConfig) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *BackendConfig) GetAllowedMethods() []string {
	if x != nil {
		return x.AllowedMethods
	}
	return nil
}

func (x *BackendConfig) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *BackendConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *BackendConfig) GetCircuitBreaker() *CircuitBreakerConfig {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Status        BackendStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=obsidian.proxy.v1.BackendStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_api_proto_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *Backend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backend) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Backend) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Backend) GetStatus() BackendStatus {
	if x != nil {
		return x.Status
	}
	return BackendStatus_BACKEND_STATUS_UNSPECIFIED
}

func (x *Backend) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Backend) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BackendID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendID) Reset() {
	*x = BackendID{}
	mi := &file_api_proto_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendID) ProtoMessage() {}

func (x *BackendID) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendID.ProtoReflect.Descriptor instead.
func (*BackendID) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *BackendID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListBackendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_api_proto_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *ListBackendsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBackendsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type BackendList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*Backend             `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendList) Reset() {
	*x = BackendList{}
	mi := &file_api_proto_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendList) ProtoMessage() {}

func (x *BackendList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendList.ProtoReflect.Descriptor instead.
func (*BackendList) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *BackendList) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *BackendList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RateLimits struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond     int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	Burst                 int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	MaxConcurrentRequests int32                  `protobuf:"varint,3,opt,name=max_concurrent_requests,json=maxConcurrentRequests,proto3" json:"max_concurrent_requests,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RateLimits) Reset() {
	*x = RateLimits{}
	mi := &file_api_proto_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimits) ProtoMessage() {}

func (x *RateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimits.ProtoReflect.Descriptor instead.
func (*RateLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *RateLimits) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *RateLimits) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *RateLimits) GetMaxConcurrentRequests() int32 {
	if x != nil {
		return x.MaxConcurrentRequests
	}
	return 0
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FilterType             `protobuf:"varint,1,opt,name=type,proto3,enum=obsidian.proxy.v1.FilterType" json:"type,omitempty"`
	Parameter     string                 `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_api_proto_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *Filter) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_FILTER_TYPE_UNSPECIFIED
}

func (x *Filter) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *Filter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CircuitBreakerConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FailureThreshold int32                  `protobuf:"varint,1,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	Timeout          *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	SuccessThreshold int32                  `protobuf:"varint,3,opt,name=success_threshold,json=successThreshold,proto3" json:"success_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CircuitBreakerConfig) Reset() {
	*x = CircuitBreakerConfig{}
	mi := &file_api_proto_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerConfig) ProtoMessage() {}

func (x *CircuitBreakerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerConfig.ProtoReflect.Descriptor instead.
func (*CircuitBreakerConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *CircuitBreakerConfig) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *CircuitBreakerConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *CircuitBreakerConfig) GetSuccessThreshold() int32 {
	if x != nil {
		return x.SuccessThreshold
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendName   string                 `protobuf:"bytes,1,opt,name=backend_name,json=backendName,proto3" json:"backend_name,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_api_proto_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *GetMetricsRequest) GetBackendName() string {
	if x != nil {
		return x.BackendName
	}
	return ""
}

func (x *GetMetricsRequest) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

type ProxyMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests       int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	SuccessfulRequests  int64                  `protobuf:"varint,2,opt,name=successful_requests,json=successfulRequests,proto3" json:"successful_requests,omitempty"`
	FailedRequests      int64                  `protobuf:"varint,3,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`
	RateLimitedRequests int64                  `protobuf:"varint,4,opt,name=rate_limited_requests,json=rateLimitedRequests,proto3" json:"rate_limited_requests,omitempty"`
	AverageLatencyMs    float64                `protobuf:"fixed64,5,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	P95LatencyMs        float64                `protobuf:"fixed64,6,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs        float64                `protobuf:"fixed64,7,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	RequestsByMethod    map[string]int64       `protobuf:"bytes,8,rep,name=requests_by_method,json=requestsByMethod,proto3" json:"requests_by_method,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RequestsByStatus    map[int32]int64        `protobuf:"bytes,9,rep,name=requests_by_status,json=requestsByStatus,proto3" json:"requests_by_status,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProxyMetrics) Reset() {
	*x = ProxyMetrics{}
	mi := &file_api_proto_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMetrics) ProtoMessage() {}

func (x *ProxyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMetrics.ProtoReflect.Descriptor instead.
func (*ProxyMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyMetrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ProxyMetrics) GetSuccessfulRequests() int64 {
	if x != nil {
		return x.SuccessfulRequests
	}
	return 0
}

func (x *ProxyMetrics) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *ProxyMetrics) GetRateLimitedRequests() int64 {
	if x != nil {
		return x.RateLimitedRequests
	}
	return 0
}

func (x *ProxyMetrics) GetAverageLatencyMs() float64 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *ProxyMetrics) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *ProxyMetrics) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *ProxyMetrics) GetRequestsByMethod() map[string]int64 {
	if x != nil {
		return x.RequestsByMethod
	}
	return nil
}

func (x *ProxyMetrics) GetRequestsByStatus() map[int32]int64 {
	if x != nil {
		return x.RequestsByStatus
	}
	return nil
}

var File_api_proto_proxy_proto protoreflect.FileDescriptor

const file_api_proto_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/proxy.proto\x12\x11obsidian.proxy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8e\x02\n" +
	"\aRequest\x12!\n" +
	"\fbackend_name\x18\x01 \x01(\tR\vbackendName\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12A\n" +
	"\aheaders\x18\x04 \x03(\v2'.obsidian.proxy.v1.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12!\n" +
	"\fcontainer_id\x18\x06 \x01(\tR\vcontainerId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf4\x01\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12B\n" +
	"\aheaders\x18\x02 \x03(\v2(.obsidian.proxy.v1.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x123\n" +
	"\alatency\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\alatency\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x02\n" +
	"\rBackendConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12>\n" +
	"\vrate_limits\x18\x03 \x01(\v2\x1d.obsidian.proxy.v1.RateLimitsR\n" +
	"rateLimits\x12'\n" +
	"\x0fallowed_methods\x18\x04 \x03(\tR\x0eallowedMethods\x123\n" +
	"\afilters\x18\x05 \x03(\v2\x19.obsidian.proxy.v1.FilterR\afilters\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12P\n" +
	"\x0fcircuit_breaker\x18\a \x01(\v2'.obsidian.proxy.v1.CircuitBreakerConfigR\x0ecircuitBreaker\"\xf9\x01\n" +
	"\aBackend\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .obsidian.proxy.v1.BackendStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1f\n" +
	"\tBackendID\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"Q\n" +
	"\x13ListBackendsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"m\n" +
	"\vBackendList\x126\n" +
	"\bbackends\x18\x01 \x03(\v2\x1a.obsidian.proxy.v1.BackendR\bbackends\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8a\x01\n" +
	"\n" +
	"RateLimits\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\x126\n" +
	"\x17max_concurrent_requests\x18\x03 \x01(\x05R\x15maxConcurrentRequests\"o\n" +
	"\x06Filter\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.obsidian.proxy.v1.FilterTypeR\x04type\x12\x1c\n" +
	"\tparameter\x18\x02 \x01(\tR\tparameter\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xa5\x01\n" +
	"\x14CircuitBreakerConfig\x12+\n" +
	"\x11failure_threshold\x18\x01 \x01(\x05R\x10failureThreshold\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12+\n" +
	"\x11success_threshold\x18\x03 \x01(\x05R\x10successThreshold\"i\n" +
	"\x11GetMetricsRequest\x12!\n" +
	"\fbackend_name\x18\x01 \x01(\tR\vbackendName\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\"\x91\x05\n" +
	"\fProxyMetrics\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12/\n" +
	"\x13successful_requests\x18\x02 \x01(\x03R\x12successfulRequests\x12'\n" +
	"\x0ffailed_requests\x18\x03 \x01(\x03R\x0efailedRequests\x122\n" +
	"\x15rate_limited_requests\x18\x04 \x01(\x03R\x13rateLimitedRequests\x12,\n" +
	"\x12average_latency_ms\x18\x05 \x01(\x01R\x10averageLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x06 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\a \x01(\x01R\fp99LatencyMs\x12c\n" +
	"\x12requests_by_method\x18\b \x03(\v25.obsidian.proxy.v1.ProxyMetrics.RequestsByMethodEntryR\x10requestsByMethod\x12c\n" +
	"\x12requests_by_status\x18\t \x03(\v25.obsidian.proxy.v1.ProxyMetrics.RequestsByStatusEntryR\x10requestsByStatus\x1aC\n" +
	"\x15RequestsByMethodEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15RequestsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*\x90\x01\n" +
	"\n" +
	"FilterType\x12\x1b\n" +
	"\x17FILTER_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FILTER_TYPE_GAS_LIMIT\x10\x01\x12\x1c\n" +
	"\x18FILTER_TYPE_CONTENT_SIZE\x10\x02\x12\x16\n" +
	"\x12FILTER_TYPE_HEADER\x10\x03\x12\x14\n" +
	"\x10FILTER_TYPE_PATH\x10\x04*\x8a\x01\n" +
	"\rBackendStatus\x12\x1e\n" +
	"\x1aBACKEND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BACKEND_STATUS_HEALTHY\x10\x01\x12\x1c\n" +
	"\x18BACKEND_STATUS_UNHEALTHY\x10\x02\x12\x1f\n" +
	"\x1bBACKEND_STATUS_CIRCUIT_OPEN\x10\x032\xea\x03\n" +
	"\fProxyService\x12G\n" +
	"\fProxyRequest\x12\x1a.obsidian.proxy.v1.Request\x1a\x1b.obsidian.proxy.v1.Response\x12J\n" +
	"\n" +
	"AddBackend\x12 .obsidian.proxy.v1.BackendConfig\x1a\x1a.obsidian.proxy.v1.Backend\x12M\n" +
	"\rUpdateBackend\x12 .obsidian.proxy.v1.BackendConfig\x1a\x1a.obsidian.proxy.v1.Backend\x12I\n" +
	"\rRemoveBackend\x12\x1c.obsidian.proxy.v1.BackendID\x1a\x1a.obsidian.proxy.v1.Backend\x12V\n" +
	"\fListBackends\x12&.obsidian.proxy.v1.ListBackendsRequest\x1a\x1e.obsidian.proxy.v1.BackendList\x12S\n" +
	"\n" +
	"GetMetrics\x12$.obsidian.proxy.v1.GetMetricsRequest\x1a\x1f.obsidian.proxy.v1.ProxyMetricsB/Z-github.com/hourglass/obsidian/api/proto/proxyb\x06proto3"

var (
	file_api_proto_proxy_proto_rawDescOnce sync.Once
	file_api_proto_proxy_proto_rawDescData []byte
)

func file_api_proto_proxy_proto_rawDescGZIP() []byte {
	file_api_proto_proxy_proto_rawDescOnce.Do(func() {
		file_api_proto_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_proxy_proto_rawDesc), len(file_api_proto_proxy_proto_rawDesc)))
	})
	return file_api_proto_proxy_proto_rawDescData
}

var file_api_proto_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_proxy_proto_goTypes = []any{
	(FilterType)(0),               // 0: obsidian.proxy.v1.FilterType
	(BackendStatus)(0),            // 1: obsidian.proxy.v1.BackendStatus
	(*Request)(nil),               // 2: obsidian.proxy.v1.Request
	(*Response)(nil),              // 3: obsidian.proxy.v1.Response
	(*BackendConfig)(nil),         // 4: obsidian.proxy.v1.BackendConfig
	(*Backend)(nil),               // 5: obsidian.proxy.v1.Backend
	(*BackendID)(nil),             // 6: obsidian.proxy.v1.BackendID
	(*ListBackendsRequest)(nil),   // 7: obsidian.proxy.v1.ListBackendsRequest
	(*BackendList)(nil),           // 8: obsidian.proxy.v1.BackendList
	(*RateLimits)(nil),            // 9: obsidian.proxy.v1.RateLimits
	(*Filter)(nil),                // 10: obsidian.proxy.v1.Filter
	(*CircuitBreakerConfig)(nil),  // 11: obsidian.proxy.v1.CircuitBreakerConfig
	(*GetMetricsRequest)(nil),     // 12: obsidian.proxy.v1.GetMetricsRequest
	(*ProxyMetrics)(nil),          // 13: obsidian.proxy.v1.ProxyMetrics
	nil,                           // 14: obsidian.proxy.v1.Request.HeadersEntry
	nil,                           // 15: obsidian.proxy.v1.Response.HeadersEntry
	nil,                           // 16: obsidian.proxy.v1.ProxyMetrics.RequestsByMethodEntry
	nil,                           // 17: obsidian.proxy.v1.ProxyMetrics.RequestsByStatusEntry
	(*durationpb.Duration)(nil),   // 18: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_api_proto_proxy_proto_depIdxs = []int32{
	14, // 0: obsidian.proxy.v1.Request.headers:type_name -> obsidian.proxy.v1.Request.HeadersEntry
	15, // 1: obsidian.proxy.v1.Response.headers:type_name -> obsidian.proxy.v1.Response.HeadersEntry
	18, // 2: obsidian.proxy.v1.Response.latency:type_name -> google.protobuf.Duration
	9,  // 3: obsidian.proxy.v1.BackendConfig.rate_limits:type_name -> obsidian.proxy.v1.RateLimits
	10, // 4: obsidian.proxy.v1.BackendConfig.filters:type_name -> obsidian.proxy.v1.Filter
	18, // 5: obsidian.proxy.v1.BackendConfig.timeout:type_name -> google.protobuf.Duration
	11, // 6: obsidian.proxy.v1.BackendConfig.circuit_breaker:type_name -> obsidian.proxy.v1.CircuitBreakerConfig
	1,  // 7: obsidian.proxy.v1.Backend.status:type_name -> obsidian.proxy.v1.BackendStatus
	19, // 8: obsidian.proxy.v1.Backend.created_at:type_name -> google.protobuf.Timestamp
	19, // 9: obsidian.proxy.v1.Backend.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 10: obsidian.proxy.v1.BackendList.backends:type_name -> obsidian.proxy.v1.Backend
	0,  // 11: obsidian.proxy.v1.Filter.type:type_name -> obsidian.proxy.v1.FilterType
	18, // 12: obsidian.proxy.v1.CircuitBreakerConfig.timeout:type_name -> google.protobuf.Duration
	18, // 13: obsidian.proxy.v1.GetMetricsRequest.window:type_name -> google.protobuf.Duration
	16, // 14: obsidian.proxy.v1.ProxyMetrics.requests_by_method:type_name -> obsidian.proxy.v1.ProxyMetrics.RequestsByMethodEntry
	17, // 15: obsidian.proxy.v1.ProxyMetrics.requests_by_status:type_name -> obsidian.proxy.v1.ProxyMetrics.RequestsByStatusEntry
	2,  // 16: obsidian.proxy.v1.ProxyService.ProxyRequest:input_type -> obsidian.proxy.v1.Request
	4,  // 17: obsidian.proxy.v1.ProxyService.AddBackend:input_type -> obsidian.proxy.v1.BackendConfig
	4,  // 18: obsidian.proxy.v1.ProxyService.UpdateBackend:input_type -> obsidian.proxy.v1.BackendConfig
	6,  // 19: obsidian.proxy.v1.ProxyService.RemoveBackend:input_type -> obsidian.proxy.v1.BackendID
	7,  // 20: obsidian.proxy.v1.ProxyService.ListBackends:input_type -> obsidian.proxy.v1.ListBackendsRequest
	12, // 21: obsidian.proxy.v1.ProxyService.GetMetrics:input_type -> obsidian.proxy.v1.GetMetricsRequest
	3,  // 22: obsidian.proxy.v1.ProxyService.ProxyRequest:output_type -> obsidian.proxy.v1.Response
	5,  // 23: obsidian.proxy.v1.ProxyService.AddBackend:output_type -> obsidian.proxy.v1.Backend
	5,  // 24: obsidian.proxy.v1.ProxyService.UpdateBackend:output_type -> obsidian.proxy.v1.Backend
	5,  // 25: obsidian.proxy.v1.ProxyService.RemoveBackend:output_type -> obsidian.proxy.v1.Backend
	8,  // 26: obsidian.proxy.v1.ProxyService.ListBackends:output_type -> obsidian.proxy.v1.BackendList
	13, // 27: obsidian.proxy.v1.ProxyService.GetMetrics:output_type -> obsidian.proxy.v1.ProxyMetrics
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_proxy_proto_init() }
func file_api_proto_proxy_proto_init() {
	if File_api_proto_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_proxy_proto_rawDesc), len(file_api_proto_proxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_proxy_proto_goTypes,
		DependencyIndexes: file_api_proto_proxy_proto_depIdxs,
		EnumInfos:         file_api_proto_proxy_proto_enumTypes,
		MessageInfos:      file_api_proto_proxy_proto_msgTypes,
	}.Build()
	File_api_proto_proxy_proto = out.File
	file_api_proto_proxy_proto_goTypes = nil
	file_api_proto_proxy_proto_depIdxs = nil
}
