debug: {{envDefault "DEBUG" "true"}}
managementServerGrpcPort: {{envDefault "AGGREGATOR_MGMT_PORT" "9010"}}

# Disable authentication for management API
authentication:
  enabled: false

storage:
  type: "memory"

operator:
  address: "{{env "OPERATOR_ADDRESS"}}"
  operatorPrivateKey:
    # Operator key is always provided as a private key
    # (keystores are converted to private keys during deployment)
    privateKey: "{{env "OPERATOR_PRIVATE_KEY"}}"
  signingKeys:
    {{if env "SYSTEM_BN254_KEYSTORE_PATH"}}
    # BN254 keystore configuration
    bls:
      keystoreFile: "{{env "SYSTEM_BN254_KEYSTORE_PATH"}}"
      password: "{{env "SYSTEM_KEYSTORE_PASSWORD"}}"
    {{end}}
    {{if or (env "SYSTEM_ECDSA_KEYSTORE_PATH") (env "SYSTEM_PRIVATE_KEY")}}
    # ECDSA configuration
    ecdsa:
      {{if env "SYSTEM_ECDSA_KEYSTORE_PATH"}}
      keystore:
        keystoreFile: "{{env "SYSTEM_ECDSA_KEYSTORE_PATH"}}"
        password: "{{env "SYSTEM_KEYSTORE_PASSWORD"}}"
      {{else}}
      privateKey: "{{env "SYSTEM_PRIVATE_KEY"}}"
      {{end}}
    {{end}}

l1ChainId: {{env "L1_CHAIN_ID"}}

chains:
  - name: "{{envDefault "L1_NETWORK_NAME" "ethereum"}}"
    network: "{{envDefault "L1_NETWORK" "mainnet"}}"
    chainId: {{env "L1_CHAIN_ID"}}
    rpcUrl: "{{env "L1_RPC_URL"}}"
    pollIntervalSeconds: {{envDefault "L1_POLL_INTERVAL" "2"}}
  {{if env "L2_CHAIN_ID"}}
  - name: "{{envDefault "L2_NETWORK_NAME" "base"}}"
    network: "{{envDefault "L2_NETWORK" "mainnet"}}"
    chainId: {{env "L2_CHAIN_ID"}}
    rpcUrl: "{{env "L2_RPC_URL"}}"
    pollIntervalSeconds: {{envDefault "L2_POLL_INTERVAL" "2"}}
  {{end}}