debug: {{envDefault "DEBUG" "true"}}
managementServerGrpcPort: {{envDefault "AGGREGATOR_MGMT_PORT" "9010"}}

# Disable authentication for management API
authentication:
  enabled: false

storage:
  type: "memory"

operator:
  address: "{{env "OPERATOR_ADDRESS"}}"
  operatorPrivateKey:
    {{if env "OPERATOR_KEYSTORE_PATH"}}
    keystore:
      keystoreFile: "{{env "OPERATOR_KEYSTORE_PATH"}}"
      password: "{{env "OPERATOR_KEYSTORE_PASSWORD"}}"
    {{else if env "OPERATOR_WEB3SIGNER_URL"}}
    remoteSignerConfig:
      url: "{{env "OPERATOR_WEB3SIGNER_URL"}}"
      {{if env "OPERATOR_WEB3SIGNER_CA_CERT"}}caCert: "{{env "OPERATOR_WEB3SIGNER_CA_CERT"}}"{{end}}
      {{if env "OPERATOR_WEB3SIGNER_CLIENT_CERT"}}cert: "{{env "OPERATOR_WEB3SIGNER_CLIENT_CERT"}}"{{end}}
      {{if env "OPERATOR_WEB3SIGNER_CLIENT_KEY"}}key: "{{env "OPERATOR_WEB3SIGNER_CLIENT_KEY"}}"{{end}}
      fromAddress: "{{env "OPERATOR_ADDRESS"}}"
      publicKey: "{{env "OPERATOR_PUBLIC_KEY"}}"
    {{else}}
    privateKey: "{{env "OPERATOR_PRIVATE_KEY"}}"
    {{end}}
  signingKeys:
    {{if env "SYSTEM_BLS_KEYSTORE_PATH"}}
    # BLS/BN254 keystore configuration
    bls:
      keystoreFile: "{{env "SYSTEM_BLS_KEYSTORE_PATH"}}"
      password: "{{env "SYSTEM_KEYSTORE_PASSWORD"}}"
    {{end}}
    {{if or (env "SYSTEM_ECDSA_KEYSTORE_PATH") (env "SYSTEM_ECDSA_WEB3SIGNER_URL") (env "SYSTEM_PRIVATE_KEY")}}
    # ECDSA configuration
    ecdsa:
      {{if env "SYSTEM_ECDSA_KEYSTORE_PATH"}}
      keystore:
        keystoreFile: "{{env "SYSTEM_ECDSA_KEYSTORE_PATH"}}"
        password: "{{env "SYSTEM_KEYSTORE_PASSWORD"}}"
      {{else if env "SYSTEM_ECDSA_WEB3SIGNER_URL"}}
      remoteSignerConfig:
        url: "{{env "SYSTEM_ECDSA_WEB3SIGNER_URL"}}"
        {{if env "SYSTEM_WEB3SIGNER_CA_CERT"}}caCert: "{{env "SYSTEM_WEB3SIGNER_CA_CERT"}}"{{end}}
        {{if env "SYSTEM_WEB3SIGNER_CLIENT_CERT"}}cert: "{{env "SYSTEM_WEB3SIGNER_CLIENT_CERT"}}"{{end}}
        {{if env "SYSTEM_WEB3SIGNER_CLIENT_KEY"}}key: "{{env "SYSTEM_WEB3SIGNER_CLIENT_KEY"}}"{{end}}
        fromAddress: "{{env "OPERATOR_ADDRESS"}}"
        publicKey: "{{env "SYSTEM_PUBLIC_KEY"}}"
      {{else}}
      privateKey: "{{env "SYSTEM_PRIVATE_KEY"}}"
      {{end}}
    {{end}}

l1ChainId: {{env "L1_CHAIN_ID"}}

chains:
  - name: "{{envDefault "L1_NETWORK_NAME" "ethereum"}}"
    network: "{{envDefault "L1_NETWORK" "mainnet"}}"
    chainId: {{env "L1_CHAIN_ID"}}
    rpcUrl: "{{env "L1_RPC_URL"}}"
    pollIntervalSeconds: {{envDefault "L1_POLL_INTERVAL" "2"}}
  {{if env "L2_CHAIN_ID"}}
  - name: "{{envDefault "L2_NETWORK_NAME" "base"}}"
    network: "{{envDefault "L2_NETWORK" "mainnet"}}"
    chainId: {{env "L2_CHAIN_ID"}}
    rpcUrl: "{{env "L2_RPC_URL"}}"
    pollIntervalSeconds: {{envDefault "L2_POLL_INTERVAL" "2"}}
  {{end}}