debug: {{envDefault "DEBUG" "true"}}

grpcPort: {{envDefault "EXECUTOR_SERVICE_PORT" "9090"}}
managementServerGrpcPort: {{envDefault "EXECUTOR_MGMT_PORT" "9091"}}
performerNetworkName: "hourglass-local_hourglass-network"

# Disable authentication for management API
authentication:
  enabled: false

storage:
  type: "memory"

l1Chain:
  chainId: {{env "L1_CHAIN_ID"}}
  rpcUrl: "{{env "L1_RPC_URL"}}"

operator:
  address: "{{env "OPERATOR_ADDRESS"}}"
  operatorPrivateKey:
    # Operator key is always provided as a private key
    # (keystores are converted to private keys during deployment)
    privateKey: "{{env "OPERATOR_PRIVATE_KEY"}}"
  signingKeys:
    {{if env "SYSTEM_BN254_KEYSTORE_PATH"}}
    # BN254 keystore configuration
    bls:
      keystoreFile: "{{env "SYSTEM_BN254_KEYSTORE_PATH"}}"
      password: "{{env "SYSTEM_KEYSTORE_PASSWORD"}}"
    {{end}}
    {{if or (env "SYSTEM_ECDSA_KEYSTORE_PATH") (env "SYSTEM_PRIVATE_KEY")}}
    # ECDSA configuration
    ecdsa:
      {{if env "SYSTEM_ECDSA_KEYSTORE_PATH"}}
      keystore:
        keystoreFile: "{{env "SYSTEM_ECDSA_KEYSTORE_PATH"}}"
        password: "{{env "SYSTEM_KEYSTORE_PASSWORD"}}"
      {{else}}
      privateKey: "{{env "SYSTEM_PRIVATE_KEY"}}"
      {{end}}
    {{end}}

# AVS performers will be managed dynamically via the management API
avsPerformers: