name: build ponos

on:
  pull_request:
    branches:
      - "*"

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Check formatting
        run: |
          cd ponos
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files are not formatted properly:"
            gofmt -d .
            exit 1
          fi
          echo "All files are formatted correctly."
  ponos-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linter
        run: |
          cd ponos
          make deps
          export PATH=$PATH:$(go env GOPATH)/bin
          make lint
  ponos-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linter
        run: |
          cd ponos
          make deps
          export PATH=$PATH:$(go env GOPATH)/bin
          make ci-test
